workload       = "eipp"
environment    = "dev"
location       = "centralus"
location_short = "cus"

owner                        = "platform-engineering"
cost_center                  = "enterprise-modernization"
invoice_storage_account_name = "steippdevdata2978a89b"
function_app_name            = "func-eipp-dev-cus-2978a89b"
function_service_plan_name   = "asp-eipp-dev-cus"
