workload       = "eipp"
environment    = "prod"
location       = "centralus"
location_short = "cus"

owner                        = "platform-engineering"
cost_center                  = "enterprise-modernization"
invoice_storage_account_name = "steippproddata2978a89b"
function_app_name            = "func-eipp-prod-cus-2978a89b"
function_service_plan_name   = "asp-eipp-prod-cus"
